// list style initializer
enum state_enum = [
	state_idle, 
	state_active, 
	state_ending,
	state_invalid = 100
];

assert(state_enum.state_idle == 0, "Enum member value initialization invalid!");
assert(state_enum.state_active == 1, "Enum member value initialization invalid!");
assert(state_enum.state_ending == 2, "Enum member value initialization invalid!");
assert(state_enum.state_invalid == 100, "Enum member value initialization invalid!");

state = state_enum.state_active;
print(state);
assert(state == 1, "Enum value identifier invalid!");

print("Get Enum name");
name = state_enum[0];
print(name);
assert(name == "state_idle", "Enum Indexof invalid!");
