function foo(): end;

if(true): 
	//foo();
	//bar(x);
	//comment
	x = 5;
	if(false): end
else:
	foo();
	// comment
	if(true):
		foo();
	else if(true):
		foo();
	else if(true):
		foo();
	else if(true):
		foo();
	else if(true):
		foo();
	else:
		foo();
	end
end

//for(5): end

//for(i in 5): end

//for(1..10): end

//for(i in 1..10): end

//while(true): end

//do while(true): end

{}

{
{{}}
{{{}}}
{{}}
}

{{{{}}}}

{
	x = 5;
	foo();
	//comment
	{
		y = 4;
		{
			z = 0;
		}
	}
	{
		// hello
	}
}

return;
return 0;
return x;
return function: end;
continue;
break;