// functions

// bare minimum. `function identifier: end;`
function x1: end;

function x2(): end;

function x3(x): end;

function x4(x, y): end;

// anonymous funcs
function: end;
function (x): end;
function (x, y): end;
x5 = function: end;
x6 = function (x): end;
x7 = function (x, y): end;

function:
	function:
		function: end;
	end;
end;

x(function: end);
x(x, function: end, x);
x(1, function: end, "a");
x("hello_world");

// evaluate lambda
x8 = (lambda:end);

// lamba implicitly evaluates as an expression
foo(lambda(x):function:end end);
foo(1, lambda(x):function:end end, 1);
foo(1, lambda(x):lambda(x):lambda(x):lambda(x):function:end end end end end, 1);