// functions

// bare minimum. `function identifier: end;`
function x1: end;

function x2(): end;

function x3(x): end;

function x4(x, y): end;

// anonymous funcs
function: end;
function (x): end;
function (x, y): end;
x5 = function: end;
x6 = function (x): end;
x7 = function (x, y): end;

function:
	function:
		function: end;
	end;
end;

function x(i): end;
x(function: end);
x("hello_world");

function y(i, j, k): end;
y(x, function: end, x);
function z(i, j, k): end;
z(1, function: end, "a");

// evaluate lambda
x8 = (lambda:print("hello") end);

// lambas get evaluated as an expression
function foo(x): end;
foo(lambda(x):function:end end);

function bar(i, j, k): end;
bar(1, lambda(x):function:end end, 1);
bar(1, lambda(x):lambda(x):lambda(x):lambda(x):function:end end end end end, 1);