// integer arithmetic
sum = 1 + 3 - 10;
print(sum);

prod = 3 * 4 / 10;
print(prod);

mod = 10 % 2;
print(mod);

// float arithmetic
flsum = 1.3 + 14.1 - 100.345;
print(flsum);

flprod = 3.1 * 9.7 / 3.5;
print(flprod);

flmod = 10.0 % 5.0;
print(flmod);

/*
// boolean arithmetic
cond1 = true && false;
print(cond1);
cond2 = 1 > 10;
print(cond2);
cond3 = 5 < 10 && (3 > 1 || 0 >= 0);
print(cond3);
cond4 = 5 != 10;
print(cond4);
cond5 = 5 == 5;
print(cond5);
